# Generated by Django 6.0 on 2026-01-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('official_title', models.CharField(help_text='مثلاً: نمایندگی رسمی سامسونگ در تهران', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='brands/favicons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='BaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('products', 'Products'), ('services', 'Services'), ('demo', 'Demo'), ('howto', 'HowTo'), ('footer', 'Footer')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.brand')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BrandSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('og_title', models.CharField(blank=True, max_length=70)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='brands/seo/')),
                ('twitter_title', models.CharField(blank=True, max_length=70)),
                ('twitter_description', models.CharField(blank=True, max_length=160)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='brands/seo/')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='main.brand')),
            ],
            options={
                'verbose_name': 'Brand SEO',
            },
        ),
        migrations.CreateModel(
            name='BrandStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0f62fe', max_length=20)),
                ('primary_dark_color', models.CharField(default='#003a8f', max_length=20)),
                ('secondary_color', models.CharField(default='#111827', max_length=20)),
                ('background_light', models.CharField(default='#f9fafb', max_length=20)),
                ('background_dark', models.CharField(default='#0b1c2d', max_length=20)),
                ('font_family', models.CharField(default='Inter, sans-serif', max_length=100)),
                ('heading_weight', models.PositiveSmallIntegerField(default=600)),
                ('body_weight', models.PositiveSmallIntegerField(default=400)),
                ('border_radius', models.PositiveSmallIntegerField(default=12, help_text='px')),
                ('button_radius', models.PositiveSmallIntegerField(default=10)),
                ('custom_css', models.TextField(blank=True, help_text='CSS مخصوص این برند (inject میشه، ولی external)')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='main.brand')),
            ],
            options={
                'verbose_name': 'Brand Style',
            },
        ),
        migrations.CreateModel(
            name='SectionCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctas', to='main.basesection')),
            ],
            options={
                'verbose_name': 'Section CTA',
            },
        ),
    ]
